# Generated by Django 3.2.15 on 2022-09-15 07:50

import apps.store.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس ')),
                ('telephone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت')),
                ('square_meter', models.FloatField(verbose_name='متراژ')),
                ('zip_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('is_active', models.BooleanField(default=True)),
                ('img_profile', models.ImageField(default='default_profile_pic.jpg', upload_to=apps.store.models.upload_profile_image_path, verbose_name='عکس پروفایل')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('img_national_card', models.ImageField(blank=True, default='', upload_to=apps.store.models.upload_document_image_path, verbose_name='تصویر کارت ملی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مغازه',
                'verbose_name_plural': 'مغازه ها ',
            },
        ),
    ]
