# Generated by Django 3.2.15 on 2022-08-30 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='عنوان تراکنش')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شماره تراکنش')),
                ('status', models.CharField(blank=True, choices=[('موفق', 'موفق'), ('ناموفق', 'ناموفق'), ('در انتظار پاسخ ', 'در انتظار پاسخ')], default='', max_length=200, verbose_name='وضعیت تراکنش')),
                ('value', models.BigIntegerField(default=0, verbose_name='مبلغ تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=200, verbose_name='تاریخ و زمان تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='current_balance',
            field=models.BigIntegerField(default=0, verbose_name='موجودی حساب'),
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallet'),
        ),
    ]
