# Generated by Django 3.2.15 on 2022-08-25 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, null=True, verbose_name='جنسیت')),
                ('birthdate', models.DateField(blank=True, max_length=50, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
