# Generated by Django 3.2.15 on 2022-08-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='img_national_card',
            field=models.ImageField(blank=True, default='', upload_to='upload_document_image_path', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='img_profile',
            field=models.ImageField(default='default_img.png', upload_to='upload_profile_image_path', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
    ]
